# -*- coding: utf-8 -*-
"""Copy of rooman_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P0lnDNL8YurvIHd5liLPfdteky0ZTjH2
"""

import gradio as gr

# Define the InterviewAgent class directly in the notebook for simplicity
# In a real application, this would ideally be in a separate agent.py file
class InterviewAgent:
    def __init__(self):
        self.questions = [
            "Tell me about yourself.",
            "Why are you interested in this role?",
            "Describe a challenging project and how you handled it.",
            "Where do you see yourself in five years?"
        ]
        self.current_question_index = 0

    def ask_question(self, job_role):
        if self.current_question_index < len(self.questions):
            question = self.questions[self.current_question_index]
            self.current_question_index += 1
            return question
        else:
            # Reset for demonstration or provide a 'no more questions' message
            self.current_question_index = 0
            return "That's all the questions for now!"

    def evaluate_response(self, response):
        # Simple placeholder for evaluation logic
        # In a real scenario, this would use an LLM or more complex logic
        score = len(response) % 10 + 1 # Dummy score based on response length
        strengths = ["Addressed the prompt"] if score > 5 else []
        weaknesses = ["Could be more detailed"] if score <= 5 else []
        suggestions = "Elaborate further on your experiences." if score <= 5 else "Good response!"

        return {
            "score": score,
            "strengths": strengths,
            "weaknesses": weaknesses,
            "suggestions": suggestions
        }

agent = InterviewAgent()
current_question = None

def start_interview(job_role):
    global current_question # Moved to the top
    current_question = agent.ask_question(job_role)
    return f"Starting interview for {job_role}. First question: {current_question}"

def evaluate_answer(response):
    global current_question # Moved to the top
    if not current_question:
        return "Please start the interview first."

    evaluation = agent.evaluate_response(response)
    feedback = f"Score: {evaluation['score']}/10\n"
    feedback += f"Strengths: {', '.join(evaluation['strengths'])}\n"
    feedback += f"Weaknesses: {', '.join(evaluation['weaknesses'])}\n"
    feedback += f"Suggestions: {evaluation['suggestions']}"
    # For demo, ask next question (simple loop)
    next_q = agent.ask_question("Default")  # Or based on role
    current_question = next_q
    feedback += f"\n\nNext question: {next_q}"

    return feedback

# Gradio Interface
with gr.Blocks() as demo:
    gr.Markdown("# Interview Agent")
    gr.Markdown("Enter a job role to start, then answer questions and get feedback.")

    job_input = gr.Textbox(label="Job Role (e.g., Software Engineer)")
    start_btn = gr.Button("Start Interview")
    question_output = gr.Textbox(label="Current Question", interactive=False)

    response_input = gr.Textbox(label="Your Answer")
    evaluate_btn = gr.Button("Submit Answer")
    feedback_output = gr.Textbox(label="Feedback", interactive=False)

    start_btn.click(start_interview, inputs=job_input, outputs=question_output)
    evaluate_btn.click(evaluate_answer, inputs=response_input, outputs=feedback_output)

if __name__ == "__main__":
    demo.launch()